### ISSUE TITLE
User can view card sets

### ISSUE THREAD

**Issue by Ortiz-Andrew** [Ortiz-Andrew/Yugioh-card-viewer#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to pick which card sets they want to see and go to their favorites list 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

allow users to pick a certain card set and go to their favorites from the home page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="282" alt="Screenshot 2023-10-03 at 10 12 36 AM" src="https://github.com/Ortiz-Andrew/ajax-project/assets/136508122/fcafb3c4-3f6c-4939-9ced-8d2f5980fd7c">
<img width="703" alt="Screenshot 2023-10-03 at 10 13 54 AM" src="https://github.com/Ortiz-Andrew/ajax-project/assets/136508122/6a1aeaf0-584b-4ab1-8be6-24fb14b04088">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
-[ ] Create the HTML structure for my header
- [x] Create the HTML structure for my pick card set 
- [x] add a click event listener to my card sets link
  - [x] inside of this, call my viewswap function to switch to the new view (card sets)
- [x] Using CSS, make sure my header and body content are responsive on both mobile and desktop
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
